heat_template_version: 2013-05-23

description: >
  HOT template that invokes subtemplates

parameters:
  key_name:
    type: string
    description: Name of keypair to assign to servers
  image_linux:
    type: string
    description: Name of image to use for GNU/Linux servers
    default: Ubuntu Server 16.04 LTS (Xenial Xerus) amd64
  sec_group_linux:
    type: comma_delimited_list
    description: Security groups
    default: default,linux
  public_net:
    type: string
    description: >
      ID or name of public network for which floating IP addresses will be allocated
    default: ext-net
 
resources:

  iac_manager:
    type: iac_manager.yaml
    properties:
      key_name:          { get_param: key_name }
      image_linux:       { get_param: image_linux }  
      public_net:        { get_param: public_net }  
      sec_group_linux:   { get_param: sec_group_linux }  


  iac_infraservices:
    type: iac_infraservices.yaml
    depends_on: iac_manager
    properties:
      key_name:          { get_param: key_name }
      image_linux:       { get_param: image_linux }
      sec_group_linux:   { get_param: sec_group_linux }
      public_net:        { get_param: public_net }
      admin_net:         { get_attr: [iac_manager,admin_net] }
      admin_subnet:      { get_attr: [iac_manager,admin_subnet] }
      other_net:         { get_attr: [iac_manager,other_net] }
      other_subnet:      { get_attr: [iac_manager,other_subnet] }
      dns_ip:            { get_attr: [iac_manager,manager_admin_ip] }
      manager_ip:        { get_attr: [iac_manager,manager_admin_ip] }


  iac_rest_1:
    type: iac_rest_1.yaml
    depends_on: iac_infraservices
    properties:
      key_name:          { get_param: key_name }
      image_linux:       { get_param: image_linux }  
      sec_group_linux:   { get_param: sec_group_linux }  
      public_net:        { get_param: public_net }  
      admin_net:         { get_attr: [iac_manager,admin_net] }
      admin_subnet:      { get_attr: [iac_manager,admin_subnet] }
      other_net:         { get_attr: [iac_manager,other_net] }
      other_subnet:      { get_attr: [iac_manager,other_subnet] }
      dns_ip:            { get_attr: [iac_manager,manager_admin_ip] }
      manager_ip:        { get_attr: [iac_manager,manager_admin_ip] }

outputs:
  manager_admin_ip:
    description: IP address of manager in the admin network
    value: { get_attr: [iac_manager,manager_admin_ip] }

